# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cafb651f0fba0d98a2a0f5b082dd4d85b9b8c3fcb6b4c157f1badff50dcfd4b90f02bdff68fad23931cbb7e48f9ad7a03fbe6733cb8da27d49056d4f773f9be1

test:
  secret_key_base: 98e520ed56a89559aea5d3f372f9a12428fea93b83ed483e9acb56c163e12908e90176d93fd2efe46e3b9ffb6c0af0e0b8b435ec1329c9a31d45f9a34b7ea50b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
